# Numpy BEG Codes

In [78]:
import numpy as np

In [79]:
myarray = np.array([1, 2, 3])
myarray

array([1, 2, 3])

In [80]:
myarray = np.array([1, 2, 3], np.int8)
myarray

array([1, 2, 3], dtype=int8)

In [81]:
myarray.shape

(3,)

In [82]:
myarray = np.array([[1, 2, 3, 8], [4, 5, 6, 7]], np.int8)
myarray

array([[1, 2, 3, 8],
       [4, 5, 6, 7]], dtype=int8)

In [83]:
myarray.shape

(2, 4)

In [84]:
myarray.dtype

dtype('int8')

In [85]:
myarray.size

8

In [86]:
zeros = np.zeros([2, 5])
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [87]:
rng = np.arange(36)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [88]:
rng.reshape(6, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [89]:
rng = rng.reshape(6, 6)
rng

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [90]:
rng.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [91]:
lsp = np.linspace(1, 50, 10)
lsp

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [92]:
emp = np.empty([4, 6])
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34605037e-307, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.29060531e-306,
        1.11261434e-306, 8.01097889e-307, 2.56765117e-312]])

In [93]:
emp_like = np.empty_like(lsp)
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [94]:
ide = np.identity(5)
ide 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [95]:
ide.shape

(5, 5)

In [96]:
x = np.zeros((8,8), dtype=int)
x

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [97]:
x[1::2, ::2] = 1
x

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])